spring.datasource.url=jdbc:postgresql://localhost:5433/librarydb_test
spring.datasource.username=${POSTGRES_USER:libraryuser}
spring.datasource.password=${POSTGRES_PASSWORD:librarypass}
spring.jpa.hibernate.ddl-auto=create-drop