spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:librarydb}
spring.datasource.username=${POSTGRES_USER:libraryuser}
spring.datasource.password=${POSTGRES_PASSWORD:librarypass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true